# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Regular + security updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily" # can be daily, weekly, or monthly
    open-pull-requests-limit: 10
    rebase-strategy: auto
    commit-message:
      prefix: "chore(deps)"
    # Enable security + version updates
    allow:
      - dependency-type: all

